### ISSUE TITLE
 Isn't `hash_index_cells_used` a meaningless value since MySQL 5.1.28?

### ISSUE THREAD

**Issue by do-su-0805** [mackerelio/mackerel-plugin-mysql#11]
According to https://dev.mysql.com/doc/mysql-em-plugin/en/myoem-metric-innodb-adaptivehashactivity-category.html and about MySQL 5.1.28 of https://downloads.mysql.com/docs/mysql-5.1-relnotes-en.pdf , `used cells` is described is not displayed.

As a result, it seems that the processing of https://github.com/mackerelio/mackerel-plugin-mysql/blob/ccc92ec3a2d56952ffbc8166625868b935d69396/lib/mysql.go#L1026 just continues to output 0.

Since mackerel-plugin-mysql 1.1.0 and later does not support MySQL 5.1, I think it is okay to delete it.

**Comment by yohfee** [comment]
Thanks!!
