### ISSUE TITLE
`unpurged_txns` is calculated but not posted

### ISSUE THREAD

**Issue by do-su-0805** [mackerelio/mackerel-plugin-mysql#12]
`unpurged_txns` is calculated at https://github.com/mackerelio/mackerel-plugin-mysql/blob/ccc92ec3a2d56952ffbc8166625868b935d69396/lib/mysql.go#L900-L908, but it is not posted anywhere.

It seems to have remained unposted since its implementation at https://github.com/mackerelio/mackerel-agent-plugins/pull/72.

**Comment by inommm** [comment]
fixed by https://github.com/mackerelio/mackerel-plugin-mysql/pull/15
